version: '3'

services:  
  db:
    image: postgres:9.6-alpine
    ports:
      - "6543:5432"
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  
  www:
    image: nginx:1.16.1-alpine
    restart: always
    expose:
      - "80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    environment:
      - VIRTUAL_HOST=sitio.local

  web:
    build: .
    command: gunicorn djangonginx.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db

  www-test:
    image: nginx:1.16.1-alpine
    restart: always
    expose:
      - "80"
    volumes:
      - /home/leonel/test/djangonginx/static:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=test.sitio.local

networks:
  default:
    ipam:
      config:
        - subnet: 172.185.0.0/16
